// Build Stoa's tokens: CSS variables (light, dark, density modes, reduced
// motion), an ES module with TypeScript declarations, and a flat JSON.
import StyleDictionary from "style-dictionary";
import { readFile, writeFile, mkdir } from "node:fs/promises";

const out = "dist/";
await mkdir(out, { recursive: true });

const base = {
  source: ["tokens/primitive.json", "tokens/semantic.light.json"],
  platforms: {
    css: {
      transformGroup: "css",
      prefix: "stoa",
      buildPath: out,
      files: [
        { destination: "light.css", format: "css/variables", options: { selector: ":root", outputReferences: true } },
      ],
    },
    js: {
      transformGroup: "js",
      buildPath: out,
      files: [
        { destination: "tokens.js", format: "javascript/es6" },
        { destination: "tokens.d.ts", format: "typescript/es6-declarations" },
        { destination: "tokens.json", format: "json/flat" },
      ],
    },
  },
};
await new StyleDictionary(base).buildAllPlatforms();

// Dark theme: only the semantic tokens change.
const semanticOnly = (token) => token.filePath.includes("semantic.");
const dark = new StyleDictionary({
  source: ["tokens/primitive.json", "tokens/semantic.dark.json"],
  platforms: {
    css: {
      transformGroup: "css",
      prefix: "stoa",
      buildPath: out,
      files: [
        { destination: "dark.css", format: "css/variables", filter: semanticOnly, options: { selector: '[data-theme="dark"]' } },
        { destination: "dark-auto.css", format: "css/variables", filter: semanticOnly, options: { selector: ':root:not([data-theme="light"])' } },
      ],
    },
  },
});
await dark.buildAllPlatforms();

// Density modes: the same variables, one selector per mode; regular is
// the default. The default block is written first: `:root` and an
// attribute selector have the same specificity, so a mode set on the root
// element (`<html data-density="compact">`) only wins when its block comes
// after `:root`.
const density = JSON.parse(await readFile("tokens/density.json", "utf8"));
const densityCss = Object.entries(density)
  .sort(([a], [b]) => Number(b === "regular") - Number(a === "regular"))
  .map(([mode, vars]) => {
    const body = Object.entries(vars)
      .map(([name, t]) => `  --stoa-density-${name}: ${t.$value};`)
      .join("\n");
    const selector = mode === "regular" ? `:root, [data-density="regular"]` : `[data-density="${mode}"]`;
    return `${selector} {\n${body}\n}`;
  })
  .join("\n\n");

const reducedMotion = `@media (prefers-reduced-motion: reduce) {
  :root {
    --stoa-motion-duration-fast: 0ms;
    --stoa-motion-duration-base: 0ms;
    --stoa-motion-duration-slow: 0ms;
    --stoa-motion-duration-flash: 0ms;
  }
}`;

// The same values gated on an attribute: a page cannot force
// prefers-reduced-motion from JavaScript, so an application's own setting,
// or a preview of one part of a page, sets data-motion="reduce" instead.
const reducedMotionAttribute = `[data-motion="reduce"] {
  --stoa-motion-duration-fast: 0ms;
  --stoa-motion-duration-base: 0ms;
  --stoa-motion-duration-slow: 0ms;
  --stoa-motion-duration-flash: 0ms;
}`;

const light = await readFile(`${out}light.css`, "utf8");
const darkCss = await readFile(`${out}dark.css`, "utf8");
const darkAuto = await readFile(`${out}dark-auto.css`, "utf8");
const css = [
  "/* Stoa tokens. Generated by scripts/build.mjs; do not edit. */",
  light,
  darkCss,
  `@media (prefers-color-scheme: dark) {\n${darkAuto}\n}`,
  densityCss,
  reducedMotion,
  reducedMotionAttribute,
  "",
].join("\n");
await writeFile(`${out}tokens.css`, css);
console.log(`tokens.css: ${css.length} bytes`);
